// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_parallax(j,f,a){var c=jQuery;var e=c(this);var b=j.parallax||0.25;var d=c("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).addClass("ws_effect ws_parallax").appendTo(a);function i(k){return Math.round(k*1000)/1000}var h=c("<div>").css({position:"absolute",left:0,top:0,overflow:"hidden",width:"100%",height:"100%",transform:"translate3d(0,0,0)"}).appendTo(d);var g=h.clone().appendTo(d);this.go=function(k,q,o){var r=c(f.get(q));r={width:r.width(),height:r.height(),marginTop:r.css("marginTop"),marginLeft:r.css("marginLeft")};o=o?1:-1;var m=c(f.get(q)).clone().css(r).appendTo(h);var n=c(f.get(k)).clone().css(r).appendTo(g);var l=a.width()||j.width;var p=a.height()||j.height;wowAnimate(function(u){u=c.easing.swing(u);var w=i(o*u*l),t=i(o*(-l+u*l)),s=i(-o*l*b*u),v=i(o*l*b*(1-u));if(j.support.transform){h.css("transform","translate3d("+w+"px,0,0)");m.css("transform","translate3d("+s+"px,0,0)");g.css("transform","translate3d("+t+"px,0,0)");n.css("transform","translate3d("+v+"px,0,0)")}else{h.css("left",w);m.css("margin-left",s);g.css("left",t);n.css("margin-left",v)}},0,1,j.duration,function(){d.hide();m.remove();n.remove();e.trigger("effectEnd")})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"parallax",prev:"",next:"",duration:20*100,delay:20*100,width:1600,height:1200,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:false,loop:false,bullets:1,caption:true,captionEffect:"parallax",controls:true,responsive:3,fullScreen:false,gestures:2,onBeforeStep:0,images:0});